SlowMC: /mnt/md0/Documents/Documents/Spring2012/211/SlowMC/src/main.f90 File Reference
main.f90 File Reference
Functions/Subroutines
program main
subroutine initialize ()
high level routine for intializing problem
subroutine run_problem ()
main routine for executing the transport calculation
subroutine finalize ()
routine that finalizes the problem
Function Documentation
subroutine main::finalize ()
routine that finalizes the problem
Definition at line 160 of file main.f90.
References global::deallocate_problem(), global::finalize_tallies(), and output::write_output().
Referenced by main().
subroutine main::initialize ()
high level routine for intializing problem
Definition at line 58 of file main.f90.
References materials::compute_macroxs(), global::mat, output::print_heading(), input::read_input(), global::seed, global::time_init, timing::timer_start(), and timing::timer_stop().
Referenced by main().
program main ()
Definition at line 1 of file main.f90.
References finalize(), initialize(), and run_problem().
subroutine main::run_problem ()
main routine for executing the transport calculation
Definition at line 99 of file main.f90.
References global::add_to_tallies(), global::eidx, global::emin, physics::get_eidx(), particle::init_particle(), global::neut, global::nhistories, physics::perform_physics(), physics::sample_source(), timing::timer_start(), and timing::timer_stop().
Referenced by main().