SlowMC: materials Module Reference
materials Module Reference
Contains information about the isotopics of problem.
Data Types
type source_type
type thermal_type
type iso_type
type material_type
Functions/Subroutines
subroutine, public setup_material (this, emin, emax)
routine that initializes the materials
subroutine, public load_isotope (this, N, A, path, thermal)
routine that loads isotope properties, xs, etc.
subroutine, public load_source (this, source_type, source_path)
routine to load fission source into memory
subroutine, public compute_totxs (this)
routine to pre-compute macroscopic total xs
subroutine, public deallocate_material (this)
routine to deallocate a material
Detailed Description
Contains information about the isotopics of problem.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine,public materials::compute_totxs (type(material_type),target this)
routine to pre-compute macroscopic total xs
Definition at line 268 of file materials.f90.
Referenced by initialize().
subroutine,public materials::deallocate_material (type(material_type) this)
routine to deallocate a material
Definition at line 302 of file materials.f90.
Referenced by global::deallocate_problem().
subroutine,public materials::load_isotope (type(material_type),target this, real(8) N, real(8) A, character(len=255) path, logical thermal)
routine that loads isotope properties, xs, etc.
into memory
Definition at line 91 of file materials.f90.
Referenced by input::read_input().
subroutine,public materials::load_source (type(material_type) this, integer source_type, character(len=255) source_path)
routine to load fission source into memory
Definition at line 211 of file materials.f90.
Referenced by input::read_input().
subroutine,public materials::setup_material (type(material_type) this, real(8) emin, real(8) emax)
routine that initializes the materials
Definition at line 67 of file materials.f90.
Referenced by input::read_input().