SlowMC: output Module Reference
output Module Reference
Contains routines for outputtting major info to user.
Functions/Subroutines
subroutine, public print_heading ()
prints the code heading and run information
subroutine get_today (today_date, today_time)
calculates information about date/time of run
Detailed Description
Contains routines for outputtting major info to user.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine output::get_today (character(10),intent(out) today_date, character(8),intent(out) today_time)
calculates information about date/time of run
Definition at line 64 of file output.f90.
Referenced by print_heading().
subroutine,public output::print_heading ()
prints the code heading and run information
Definition at line 22 of file output.f90.
References get_today(), global::VERSION_MAJOR, global::VERSION_MINOR, and global::VERSION_RELEASE.
Referenced by initialize().