SlowMC: read_xml_primitives Module Reference
read_xml_primitives Module Reference
Data Types
interface read_from_buffer
Functions/Subroutines
subroutine skip_until_endtag (info, tag, attribs, data, error)
subroutine read_xml_integer (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_line (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_real (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_double (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_logical (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_word (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_integer_array (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_line_array (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_real_array (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_double_array (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_logical_array (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_word_array (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_integer_1dim (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_real_1dim (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_double_1dim (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_logical_1dim (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_word_1dim (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
subroutine read_xml_line_1dim (info, tag, endtag, attribs, noattribs, data, nodata, var, has_var)
Function/Subroutine Documentation
subroutine read_xml_primitives::read_xml_double (info , tag , endtag , attribs , noattribs , data , nodata , real(kind=kind(1.0d00)),intent(inout) var, has_var)
Definition at line 160 of file read_xml_primitives.f90.
Referenced by read_xml_double_1dim().
subroutine read_xml_primitives::read_xml_double_1dim (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, real(kind=kind(1.0d00)),dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 414 of file read_xml_primitives.f90.
References read_xml_double().
subroutine read_xml_primitives::read_xml_double_array (info , tag , endtag , attribs , noattribs , data , nodata , real(kind=kind(1.0d00)),dimension(:),pointer var, has_var)
Definition at line 280 of file read_xml_primitives.f90.
subroutine read_xml_primitives::read_xml_integer (info , tag , endtag , attribs , noattribs , data , nodata , integer,intent(inout) var, has_var)
Definition at line 91 of file read_xml_primitives.f90.
Referenced by read_xml_integer_1dim().
subroutine read_xml_primitives::read_xml_integer_1dim (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, integer,dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 358 of file read_xml_primitives.f90.
References read_xml_integer().
subroutine read_xml_primitives::read_xml_integer_array (info , tag , endtag , attribs , noattribs , data , nodata , integer,dimension(:),pointer var, has_var)
Definition at line 199 of file read_xml_primitives.f90.
subroutine read_xml_primitives::read_xml_line (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, character(len=*),intent(inout) var, logical,intent(inout) has_var)
Definition at line 113 of file read_xml_primitives.f90.
References xmlparse::xml_find_attrib().
Referenced by read_xml_line_1dim().
subroutine read_xml_primitives::read_xml_line_1dim (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, character(len=*),dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 498 of file read_xml_primitives.f90.
References read_xml_line().
subroutine read_xml_primitives::read_xml_line_array (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, character(len=*),dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 220 of file read_xml_primitives.f90.
References xmlparse::xml_find_attrib().
subroutine read_xml_primitives::read_xml_logical (info , tag , endtag , attribs , noattribs , data , nodata , logical,intent(inout) var, has_var)
Definition at line 168 of file read_xml_primitives.f90.
Referenced by read_xml_logical_1dim().
subroutine read_xml_primitives::read_xml_logical_1dim (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, logical,dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 442 of file read_xml_primitives.f90.
References read_xml_logical().
subroutine read_xml_primitives::read_xml_logical_array (info , tag , endtag , attribs , noattribs , data , nodata , logical,dimension(:),pointer var, has_var)
Definition at line 288 of file read_xml_primitives.f90.
subroutine read_xml_primitives::read_xml_real (info , tag , endtag , attribs , noattribs , data , nodata , real,intent(inout) var, has_var)
Definition at line 152 of file read_xml_primitives.f90.
Referenced by read_xml_real_1dim().
subroutine read_xml_primitives::read_xml_real_1dim (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, real,dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 386 of file read_xml_primitives.f90.
References read_xml_real().
subroutine read_xml_primitives::read_xml_real_array (info , tag , endtag , attribs , noattribs , data , nodata , real,dimension(:),pointer var, has_var)
Definition at line 272 of file read_xml_primitives.f90.
subroutine read_xml_primitives::read_xml_word (info , tag , endtag , attribs , noattribs , data , nodata , character(len=*),intent(inout) var, has_var)
Definition at line 176 of file read_xml_primitives.f90.
Referenced by read_xml_word_1dim().
subroutine read_xml_primitives::read_xml_word_1dim (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) nodata, character(len=*),dimension(:),pointer var, logical,intent(inout) has_var)
Definition at line 470 of file read_xml_primitives.f90.
References read_xml_word().
subroutine read_xml_primitives::read_xml_word_array (info , tag , endtag , attribs , noattribs , data , nodata , character(len=*),dimension(:),pointer var, has_var)
Definition at line 296 of file read_xml_primitives.f90.
subroutine read_xml_primitives::skip_until_endtag (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, character(len=*),dimension(:,:),intent(inout) attribs, character(len=*),dimension(:),intent(inout) data, logical,intent(out) error)
Definition at line 50 of file read_xml_primitives.f90.
References xmlparse::xml_error(), and xmlparse::xml_get().