SlowMC: xml_data_input_t Module Reference
xml_data_input_t Module Reference
Data Types
type settings_xml
type nuclide_xml
type material_xml
type materials_xml
type tally_xml
type tallies_xml
Functions/Subroutines
subroutine read_xml_type_settings_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_settings_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_settings_xml_array (dvar)
subroutine init_xml_type_settings_xml (dvar)
subroutine write_xml_type_settings_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_settings_xml (info, tag, indent, dvar)
subroutine read_xml_type_nuclide_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_nuclide_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_nuclide_xml_array (dvar)
subroutine init_xml_type_nuclide_xml (dvar)
subroutine write_xml_type_nuclide_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_nuclide_xml (info, tag, indent, dvar)
subroutine read_xml_type_material_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_material_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_material_xml_array (dvar)
subroutine init_xml_type_material_xml (dvar)
subroutine write_xml_type_material_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_material_xml (info, tag, indent, dvar)
subroutine read_xml_type_materials_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_materials_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_materials_xml_array (dvar)
subroutine init_xml_type_materials_xml (dvar)
subroutine write_xml_type_materials_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_materials_xml (info, tag, indent, dvar)
subroutine read_xml_type_tally_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_tally_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_tally_xml_array (dvar)
subroutine init_xml_type_tally_xml (dvar)
subroutine write_xml_type_tally_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_tally_xml (info, tag, indent, dvar)
subroutine read_xml_type_tallies_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_tallies_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_tallies_xml_array (dvar)
subroutine init_xml_type_tallies_xml (dvar)
subroutine write_xml_type_tallies_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_tallies_xml (info, tag, indent, dvar)
subroutine read_xml_file_input_t (fname, lurep, errout)
subroutine write_xml_file_input_t (fname, lurep)
subroutine init_xml_file_input_t
Variables
integer, private lurep_
logical, private strict_
type(settings_xml) settings_
type(materials_xml) materials_
type(tallies_xml) tallies_
Function/Subroutine Documentation
subroutine xml_data_input_t::init_xml_file_input_t ()
Definition at line 1269 of file input_t.f90.
Referenced by read_xml_file_input_t().
subroutine xml_data_input_t::init_xml_type_material_xml (type(material_xml) dvar)
Definition at line 619 of file input_t.f90.
Referenced by read_xml_type_material_xml().
subroutine xml_data_input_t::init_xml_type_material_xml_array (type(material_xml),dimension(:),pointer dvar)
Definition at line 612 of file input_t.f90.
subroutine xml_data_input_t::init_xml_type_materials_xml (type(materials_xml) dvar)
Definition at line 773 of file input_t.f90.
Referenced by read_xml_type_materials_xml().
subroutine xml_data_input_t::init_xml_type_materials_xml_array (type(materials_xml),dimension(:),pointer dvar)
Definition at line 766 of file input_t.f90.
subroutine xml_data_input_t::init_xml_type_nuclide_xml (type(nuclide_xml) dvar)
Definition at line 442 of file input_t.f90.
Referenced by read_xml_type_nuclide_xml().
subroutine xml_data_input_t::init_xml_type_nuclide_xml_array (type(nuclide_xml),dimension(:),pointer dvar)
Definition at line 435 of file input_t.f90.
subroutine xml_data_input_t::init_xml_type_settings_xml (type(settings_xml) dvar)
Definition at line 235 of file input_t.f90.
Referenced by read_xml_type_settings_xml().
subroutine xml_data_input_t::init_xml_type_settings_xml_array (type(settings_xml),dimension(:),pointer dvar)
Definition at line 228 of file input_t.f90.
subroutine xml_data_input_t::init_xml_type_tallies_xml (type(tallies_xml) dvar)
Definition at line 1117 of file input_t.f90.
Referenced by read_xml_type_tallies_xml().
subroutine xml_data_input_t::init_xml_type_tallies_xml_array (type(tallies_xml),dimension(:),pointer dvar)
Definition at line 1110 of file input_t.f90.
subroutine xml_data_input_t::init_xml_type_tally_xml (type(tally_xml) dvar)
Definition at line 960 of file input_t.f90.
Referenced by read_xml_type_tally_xml().
subroutine xml_data_input_t::init_xml_type_tally_xml_array (type(tally_xml),dimension(:),pointer dvar)
Definition at line 953 of file input_t.f90.
subroutine xml_data_input_t::read_xml_file_input_t (character(len=*),intent(in) fname, integer,intent(in),optional lurep, logical,intent(out),optional errout)
Definition at line 1147 of file input_t.f90.
References init_xml_file_input_t(), lurep_, materials_, read_xml_type_materials_xml(), read_xml_type_settings_xml(), read_xml_type_tallies_xml(), settings_, strict_, and tallies_.
Referenced by input::read_input().
subroutine xml_data_input_t::read_xml_type_material_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(material_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 503 of file input_t.f90.
References init_xml_type_material_xml(), lurep_, read_xml_type_nuclide_xml_array(), and strict_.
Referenced by read_xml_type_material_xml_array().
subroutine xml_data_input_t::read_xml_type_material_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(material_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 477 of file input_t.f90.
References read_xml_type_material_xml().
Referenced by read_xml_type_materials_xml().
subroutine xml_data_input_t::read_xml_type_materials_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(materials_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 677 of file input_t.f90.
References init_xml_type_materials_xml(), lurep_, read_xml_type_material_xml_array(), and strict_.
Referenced by read_xml_file_input_t(), and read_xml_type_materials_xml_array().
subroutine xml_data_input_t::read_xml_type_materials_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(materials_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 651 of file input_t.f90.
References read_xml_type_materials_xml().
subroutine xml_data_input_t::read_xml_type_nuclide_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(nuclide_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 297 of file input_t.f90.
References init_xml_type_nuclide_xml(), lurep_, and strict_.
Referenced by read_xml_type_nuclide_xml_array().
subroutine xml_data_input_t::read_xml_type_nuclide_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(nuclide_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 271 of file input_t.f90.
References read_xml_type_nuclide_xml().
Referenced by read_xml_type_material_xml().
subroutine xml_data_input_t::read_xml_type_settings_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(settings_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 80 of file input_t.f90.
References init_xml_type_settings_xml(), lurep_, and strict_.
Referenced by read_xml_file_input_t(), and read_xml_type_settings_xml_array().
subroutine xml_data_input_t::read_xml_type_settings_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(settings_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 54 of file input_t.f90.
References read_xml_type_settings_xml().
subroutine xml_data_input_t::read_xml_type_tallies_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(tallies_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 1021 of file input_t.f90.
References init_xml_type_tallies_xml(), lurep_, read_xml_type_tally_xml_array(), and strict_.
Referenced by read_xml_file_input_t(), and read_xml_type_tallies_xml_array().
subroutine xml_data_input_t::read_xml_type_tallies_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(tallies_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 995 of file input_t.f90.
References read_xml_type_tallies_xml().
subroutine xml_data_input_t::read_xml_type_tally_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(tally_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 829 of file input_t.f90.
References init_xml_type_tally_xml(), lurep_, and strict_.
Referenced by read_xml_type_tally_xml_array().
subroutine xml_data_input_t::read_xml_type_tally_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(tally_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 803 of file input_t.f90.
References read_xml_type_tally_xml().
Referenced by read_xml_type_tallies_xml().
subroutine xml_data_input_t::write_xml_file_input_t (character(len=*),intent(in) fname, integer,intent(in),optional lurep)
Definition at line 1248 of file input_t.f90.
References materials_, settings_, tallies_, write_xml_type_materials_xml(), write_xml_type_settings_xml(), and write_xml_type_tallies_xml().
subroutine xml_data_input_t::write_xml_type_material_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(material_xml) dvar)
Definition at line 634 of file input_t.f90.
References write_xml_type_nuclide_xml_array().
Referenced by write_xml_type_material_xml_array().
subroutine xml_data_input_t::write_xml_type_material_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(material_xml),dimension(:) dvar)
Definition at line 622 of file input_t.f90.
References write_xml_type_material_xml().
Referenced by write_xml_type_materials_xml().
subroutine xml_data_input_t::write_xml_type_materials_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(materials_xml) dvar)
Definition at line 788 of file input_t.f90.
References write_xml_type_material_xml_array().
Referenced by write_xml_file_input_t(), and write_xml_type_materials_xml_array().
subroutine xml_data_input_t::write_xml_type_materials_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(materials_xml),dimension(:) dvar)
Definition at line 776 of file input_t.f90.
References write_xml_type_materials_xml().
subroutine xml_data_input_t::write_xml_type_nuclide_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(nuclide_xml) dvar)
Definition at line 457 of file input_t.f90.
Referenced by write_xml_type_nuclide_xml_array().
subroutine xml_data_input_t::write_xml_type_nuclide_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(nuclide_xml),dimension(:) dvar)
Definition at line 445 of file input_t.f90.
References write_xml_type_nuclide_xml().
Referenced by write_xml_type_material_xml().
subroutine xml_data_input_t::write_xml_type_settings_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(settings_xml) dvar)
Definition at line 250 of file input_t.f90.
Referenced by write_xml_file_input_t(), and write_xml_type_settings_xml_array().
subroutine xml_data_input_t::write_xml_type_settings_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(settings_xml),dimension(:) dvar)
Definition at line 238 of file input_t.f90.
References write_xml_type_settings_xml().
subroutine xml_data_input_t::write_xml_type_tallies_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(tallies_xml) dvar)
Definition at line 1132 of file input_t.f90.
References write_xml_type_tally_xml_array().
Referenced by write_xml_file_input_t(), and write_xml_type_tallies_xml_array().
subroutine xml_data_input_t::write_xml_type_tallies_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(tallies_xml),dimension(:) dvar)
Definition at line 1120 of file input_t.f90.
References write_xml_type_tallies_xml().
subroutine xml_data_input_t::write_xml_type_tally_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(tally_xml) dvar)
Definition at line 976 of file input_t.f90.
Referenced by write_xml_type_tally_xml_array().
subroutine xml_data_input_t::write_xml_type_tally_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(tally_xml),dimension(:) dvar)
Definition at line 964 of file input_t.f90.
References write_xml_type_tally_xml().
Referenced by write_xml_type_tallies_xml().
Variable Documentation
integer,private xml_data_input_t::lurep_
Definition at line 7 of file input_t.f90.
Referenced by read_xml_file_input_t(), read_xml_type_material_xml(), read_xml_type_materials_xml(), read_xml_type_nuclide_xml(), read_xml_type_settings_xml(), read_xml_type_tallies_xml(), and read_xml_type_tally_xml().
type(materials_xml) xml_data_input_t::materials_
Definition at line 51 of file input_t.f90.
Referenced by input::read_input(), read_xml_file_input_t(), and write_xml_file_input_t().
type(settings_xml) xml_data_input_t::settings_
Definition at line 50 of file input_t.f90.
Referenced by input::read_input(), read_xml_file_input_t(), and write_xml_file_input_t().
logical,private xml_data_input_t::strict_
Definition at line 8 of file input_t.f90.
Referenced by read_xml_file_input_t(), read_xml_type_material_xml(), read_xml_type_materials_xml(), read_xml_type_nuclide_xml(), read_xml_type_settings_xml(), read_xml_type_tallies_xml(), and read_xml_type_tally_xml().
type(tallies_xml) xml_data_input_t::tallies_
Definition at line 52 of file input_t.f90.
Referenced by input::read_input(), read_xml_file_input_t(), and write_xml_file_input_t().