SlowMC: physics Module Reference
physics Module Reference
Contains routines to model the physics of the problem.
Functions/Subroutines
subroutine, public sample_source ()
routine to sample source from cdf
subroutine, public perform_physics ()
high level routine to perform transport physics
integer, public get_eidx (E)
function to compute the index in unionized energy grid
integer sample_region ()
function to sample region where interaction occurs
integer sample_isotope (region)
function to sample interaction isotope
integer sample_reaction (region, isoidx)
function to sample reaction type
subroutine elastic_scattering (region, isoidx)
routine to perform thermal/asymptotic elastic scattering physics
Detailed Description
Contains routines to model the physics of the problem.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine physics::elastic_scattering (integer region, integer isoidx)
routine to perform thermal/asymptotic elastic scattering physics
Definition at line 303 of file physics.f90.
References global::kT, global::mat, and global::neut.
Referenced by perform_physics().
integer,public physics::get_eidx (real(8) E)
function to compute the index in unionized energy grid
Definition at line 89 of file physics.f90.
References global::mat.
Referenced by run_problem().
subroutine,public physics::perform_physics ()
high level routine to perform transport physics
Definition at line 54 of file physics.f90.
References global::add_to_tallies(), elastic_scattering(), global::n_abs, global::n_fiss, global::neut, sample_isotope(), sample_reaction(), and sample_region().
Referenced by run_problem().
integer physics::sample_isotope (integer region)
function to sample interaction isotope
Definition at line 199 of file physics.f90.
References global::eidx, and global::mat.
Referenced by perform_physics().
integer physics::sample_reaction (integer region, integer isoidx)
function to sample reaction type
Definition at line 257 of file physics.f90.
References global::eidx, and global::mat.
Referenced by perform_physics().
integer physics::sample_region ()
function to sample region where interaction occurs
Definition at line 115 of file physics.f90.
References global::Dancoff, global::eidx, global::mat, global::n_materials, global::neut, and global::radius.
Referenced by perform_physics().
subroutine,public physics::sample_source ()
routine to sample source from cdf
Definition at line 22 of file physics.f90.
References global::mat, and global::neut.
Referenced by run_problem().