SlowMC: write_xml_primitives Module Reference
write_xml_primitives Module Reference
Data Types
interface write_to_xml_word
interface write_to_xml_line
Functions/Subroutines
subroutine write_to_xml_integer (info, tag, indent, value)
subroutine write_to_xml_integer_1dim (info, tag, indent, values)
subroutine write_to_xml_real (info, tag, indent, value)
subroutine write_to_xml_real_1dim (info, tag, indent, values)
subroutine write_to_xml_double (info, tag, indent, value)
subroutine write_to_xml_double_1dim (info, tag, indent, values)
subroutine write_to_xml_string (info, tag, indent, value)
subroutine write_to_xml_word_1dim (info, tag, indent, values)
subroutine write_to_xml_string_1dim (info, tag, indent, values)
subroutine write_to_xml_logical (info, tag, indent, value)
subroutine write_to_xml_logical_1dim (info, tag, indent, values)
subroutine write_to_xml_integer_array (info, tag, indent, array)
subroutine write_to_xml_real_array (info, tag, indent, array)
subroutine write_to_xml_double_array (info, tag, indent, array)
subroutine write_to_xml_logical_array (info, tag, indent, array)
subroutine write_to_xml_word_array (info, tag, indent, array)
subroutine write_to_xml_line_array (info, tag, indent, array)
Function/Subroutine Documentation
subroutine write_xml_primitives::write_to_xml_double (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, real(kind=kind(1.0d0)),intent(in) value)
Definition at line 136 of file write_xml_primitives.f90.
Referenced by write_to_xml_double_1dim().
subroutine write_xml_primitives::write_to_xml_double_1dim (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, real(kind=kind(1.0d00)),dimension(:),intent(in) values)
Definition at line 161 of file write_xml_primitives.f90.
References write_to_xml_double().
subroutine write_xml_primitives::write_to_xml_double_array (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, real(kind=kind(1.0d0)),dimension(:),intent(in) array)
Definition at line 371 of file write_xml_primitives.f90.
subroutine write_xml_primitives::write_to_xml_integer (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, integer,intent(in) value)
Definition at line 42 of file write_xml_primitives.f90.
Referenced by write_to_xml_integer_1dim().
subroutine write_xml_primitives::write_to_xml_integer_1dim (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, integer,dimension(:),intent(in) values)
Definition at line 65 of file write_xml_primitives.f90.
References write_to_xml_integer().
subroutine write_xml_primitives::write_to_xml_integer_array (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, integer,dimension(:),intent(in) array)
Definition at line 307 of file write_xml_primitives.f90.
subroutine write_xml_primitives::write_to_xml_line_array (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, logical,dimension(:),intent(in) array)
Definition at line 467 of file write_xml_primitives.f90.
subroutine write_xml_primitives::write_to_xml_logical (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, logical,intent(in) value)
Definition at line 256 of file write_xml_primitives.f90.
Referenced by write_to_xml_logical_1dim().
subroutine write_xml_primitives::write_to_xml_logical_1dim (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, logical,dimension(:),intent(in) values)
Definition at line 284 of file write_xml_primitives.f90.
References write_to_xml_logical().
subroutine write_xml_primitives::write_to_xml_logical_array (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, logical,dimension(:),intent(in) array)
Definition at line 403 of file write_xml_primitives.f90.
subroutine write_xml_primitives::write_to_xml_real (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, real,intent(in) value)
Definition at line 88 of file write_xml_primitives.f90.
Referenced by write_to_xml_real_1dim().
subroutine write_xml_primitives::write_to_xml_real_1dim (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, real,dimension(:),intent(in) values)
Definition at line 113 of file write_xml_primitives.f90.
References write_to_xml_real().
subroutine write_xml_primitives::write_to_xml_real_array (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, real,dimension(:),intent(in) array)
Definition at line 339 of file write_xml_primitives.f90.
subroutine write_xml_primitives::write_to_xml_string (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, character(len=*),intent(in) value)
Definition at line 184 of file write_xml_primitives.f90.
Referenced by write_to_xml_string_1dim(), and write_to_xml_word_1dim().
subroutine write_xml_primitives::write_to_xml_string_1dim (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, character(len=*),dimension(:),intent(in) values)
Definition at line 233 of file write_xml_primitives.f90.
References write_to_xml_string().
subroutine write_xml_primitives::write_to_xml_word_1dim (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, character(len=*),dimension(:),intent(in) values)
Definition at line 211 of file write_xml_primitives.f90.
References write_to_xml_string().
subroutine write_xml_primitives::write_to_xml_word_array (type(XML_PARSE),intent(in) info, character(len=*),intent(in) tag, integer,intent(in) indent, character(len=*),dimension(:),intent(in) array)
Definition at line 435 of file write_xml_primitives.f90.