SlowMC: xmlparse Module Reference
xmlparse Module Reference
Data Types
type XML_PARSE
interface xml_report_details
interface xml_report_errors
Functions/Subroutines
subroutine xml_report_errors_extern_ (info, text)
subroutine xml_open (info, fname, mustread)
subroutine xml_close (info)
subroutine xml_get (info, tag, endtag, attribs, no_attribs, data, no_data)
subroutine xml_put (info, tag, attribs, no_attribs, data, no_data, type)
subroutine xml_options (info, ignore_whitespace, no_data_truncation, report_lun, report_errors, report_details)
logical xml_ok (info)
logical xml_error (info)
logical xml_data_trunc (info)
integer xml_find_attrib (attribs, no_attribs, name, value)
recursive subroutine xml_process (filename, attribs, data, startfunc, datafunc, endfunc, lunrep, error)
Variables
integer, parameter XML_BUFFER_LENGTH = 10000
integer, parameter XML_STDOUT = -1
integer, private report_lun_ = XML_STDOUT
logical, private report_errors_ = .false.
logical, private report_details_ = .false.
character(len=10), dimension(2,
3), save, private entities = reshape((/ '& ', '&amp;', '> ', '&gt; ', '< ', '&lt; ' /), (/2,3/))
Function/Subroutine Documentation
subroutine xmlparse::xml_close (type(XML_PARSE),intent(inout) info)
Definition at line 332 of file xmlparse.f90.
Referenced by endfunc::endfunc(), get_global_options(), xml_get(), and xml_open().
logical xmlparse::xml_data_trunc (type(XML_PARSE),intent(in) info)
Definition at line 932 of file xmlparse.f90.
logical xmlparse::xml_error (type(XML_PARSE),intent(in) info)
Definition at line 915 of file xmlparse.f90.
Referenced by endfunc::endfunc(), read_xml_primitives::skip_until_endtag(), and xmlreader().
integer xmlparse::xml_find_attrib (character(len=*),dimension(:,:) attribs, integer no_attribs, character(len=*) name, character(len=*) value)
Definition at line 942 of file xmlparse.f90.
Referenced by add_placeholder(), add_typedef(), add_variable(), read_xml_primitives::read_xml_line(), and read_xml_primitives::read_xml_line_array().
subroutine xmlparse::xml_get (type(XML_PARSE),intent(inout) info, character(len=*),intent(out) tag, logical,intent(out) endtag, character(len=*),dimension(:,:),intent(out) attribs, integer,intent(out) no_attribs, character(len=*),dimension(:),intent(out) data, integer,intent(out) no_data)
Definition at line 358 of file xmlparse.f90.
References xml_close().
Referenced by endfunc::endfunc(), get_global_options(), read_xml_primitives::skip_until_endtag(), and xmlreader().
logical xmlparse::xml_ok (type(XML_PARSE),intent(in) info)
Definition at line 897 of file xmlparse.f90.
Referenced by endfunc::endfunc(), get_global_options(), and xmlreader().
subroutine xmlparse::xml_open (type(XML_PARSE),intent(out) info, character(len=*),intent(in) fname, logical,intent(in) mustread)
Definition at line 252 of file xmlparse.f90.
References xml_close().
Referenced by endfunc::endfunc(), get_global_options(), and xmlreader().
subroutine xmlparse::xml_options (type(XML_PARSE),intent(inout) info, logical,intent(in),optional ignore_whitespace, logical,intent(in),optional no_data_truncation, integer,intent(in),optional report_lun, logical,intent(in),optional report_errors, logical,intent(in),optional report_details)
Definition at line 860 of file xmlparse.f90.
References report_details_, report_errors_, and report_lun_.
Referenced by endfunc::endfunc(), and xmlreader().
recursive subroutine xmlparse::xml_process (character(len=*) filename, character(len=*),dimension(:,:) attribs, character(len=*),dimension(:) data, startfunc startfunc, datafunc datafunc, endfunc endfunc, integer lunrep, logical error)
Definition at line 978 of file xmlparse.f90.
subroutine xmlparse::xml_put (type(XML_PARSE),intent(inout) info, character(len=*),intent(in) tag, character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) no_attribs, character(len=*),dimension(:),intent(in) data, integer,intent(in) no_data, character(len=*) type)
Definition at line 614 of file xmlparse.f90.
References entities.
subroutine xmlparse::xml_report_errors_extern_ (type(XML_PARSE),intent(in) info, character(len=*),intent(in) text)
Definition at line 229 of file xmlparse.f90.
References report_details_, report_errors_, report_lun_, and XML_STDOUT.
Variable Documentation
character(len=10),dimension(2,3),save,private xmlparse::entities = reshape((/ '& ', '&amp;', '> ', '&gt; ', '< ', '&lt; ' /), (/2,3/))
Definition at line 81 of file xmlparse.f90.
Referenced by xml_put().
logical,private xmlparse::report_details_ = .false.
Definition at line 75 of file xmlparse.f90.
Referenced by xml_options(), xmlparse::xml_report_details::xml_report_details_int_(), xmlparse::xml_report_details::xml_report_details_string_(), xml_report_errors_extern_(), xmlparse::xml_report_errors::xml_report_errors_int_(), and xmlparse::xml_report_errors::xml_report_errors_string_().
logical,private xmlparse::report_errors_ = .false.
Definition at line 74 of file xmlparse.f90.
Referenced by xml_options(), xml_report_errors_extern_(), xmlparse::xml_report_errors::xml_report_errors_int_(), and xmlparse::xml_report_errors::xml_report_errors_string_().
integer,private xmlparse::report_lun_ = XML_STDOUT
Definition at line 73 of file xmlparse.f90.
Referenced by xml_options(), xmlparse::xml_report_details::xml_report_details_int_(), xmlparse::xml_report_details::xml_report_details_string_(), xml_report_errors_extern_(), xmlparse::xml_report_errors::xml_report_errors_int_(), and xmlparse::xml_report_errors::xml_report_errors_string_().
integer,parameter xmlparse::XML_BUFFER_LENGTH = 10000
Definition at line 49 of file xmlparse.f90.
integer,parameter xmlparse::XML_STDOUT = -1
Definition at line 72 of file xmlparse.f90.
Referenced by xmlparse::xml_report_details::xml_report_details_int_(), xmlparse::xml_report_details::xml_report_details_string_(), xml_report_errors_extern_(), xmlparse::xml_report_errors::xml_report_errors_int_(), and xmlparse::xml_report_errors::xml_report_errors_string_().