SlowMC: global Module Reference
global Module Reference
Contains all of the global variables.
Functions/Subroutines
subroutine allocate_problem ()
allocates global variables for calculation
subroutine deallocate_problem ()
deallocates global variables
subroutine compute_macro_cross_sections ()
routine that handles the call to compute macro cross sections
subroutine add_to_tallies ()
routine that adds temporary value to tallies
subroutine bank_tallies ()
routine that record temporary history information in tallies
subroutine finalize_tallies ()
routine that calls another routine to compute tally statistics
Variables
integer VERSION_MAJOR = 0
integer VERSION_MINOR = 1
integer VERSION_RELEASE = 1
type(particle_type) neut
type(material_type), dimension(:),
allocatable mat
type(tally_type), dimension(:),
allocatable tal
integer nhistories
integer seed
integer source_type
integer eidx
integer n_tallies
integer n_materials
integer res_iso
real(8) Dancoff
real(8) radius
real(8) emin = 1e-11_8
real(8) emax = 20.0_8
real(8) kT = 8.6173324e-5_8*300*1.0e-6_8
real(8) nubar = 2.455_8
type(Timer) time_init
type(Timer) time_run
integer n_abs = 0.0_8
integer n_fiss = 0.0_8
real(8) ana_kinf_mean = 0.0_8
real(8) ana_kinf_std = 0.0_8
real(8) col_kinf_mean = 0.0_8
real(8) col_kinf_std = 0.0_8
Detailed Description
Contains all of the global variables.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine global::add_to_tallies ()
routine that adds temporary value to tallies
Definition at line 145 of file global.f90.
References tally::add_to_tally(), eidx, mat, n_tallies, neut, nubar, and tal.
Referenced by physics::perform_physics().
subroutine global::allocate_problem ()
allocates global variables for calculation
Definition at line 71 of file global.f90.
References mat, n_materials, n_tallies, and tal.
subroutine global::bank_tallies ()
routine that record temporary history information in tallies
Definition at line 222 of file global.f90.
References tally::bank_tally(), n_tallies, and tal.
Referenced by run_problem().
subroutine global::compute_macro_cross_sections ()
routine that handles the call to compute macro cross sections
Definition at line 123 of file global.f90.
References materials::compute_macroxs(), mat, and n_materials.
subroutine global::deallocate_problem ()
deallocates global variables
Definition at line 86 of file global.f90.
References materials::deallocate_material(), tally::deallocate_tally(), mat, n_materials, n_tallies, and tal.
Referenced by finalize().
subroutine global::finalize_tallies ()
routine that calls another routine to compute tally statistics
Definition at line 244 of file global.f90.
References ana_kinf_mean, ana_kinf_std, tally::calculate_statistics(), col_kinf_mean, col_kinf_std, mat, n_fiss, n_materials, n_tallies, nhistories, nubar, and tal.
Referenced by finalize().
Variable Documentation
real(8) global::ana_kinf_mean = 0.0_8
Definition at line 59 of file global.f90.
Referenced by finalize_tallies(), and output::write_output().
real(8) global::ana_kinf_std = 0.0_8
Definition at line 60 of file global.f90.
Referenced by finalize_tallies().
real(8) global::col_kinf_mean = 0.0_8
Definition at line 61 of file global.f90.
Referenced by finalize_tallies().
real(8) global::col_kinf_std = 0.0_8
Definition at line 62 of file global.f90.
Referenced by finalize_tallies().
real(8) global::Dancoff
Definition at line 39 of file global.f90.
Referenced by physics::sample_region().
integer global::eidx
Definition at line 35 of file global.f90.
Referenced by add_to_tallies(), run_problem(), physics::sample_isotope(), physics::sample_reaction(), and physics::sample_region().
real(8) global::emax = 20.0_8
Definition at line 44 of file global.f90.
Referenced by input::read_input().
real(8) global::emin = 1e-11_8
Definition at line 43 of file global.f90.
Referenced by input::read_input(), and run_problem().
real(8) global::kT = 8.6173324e-5_8*300*1.0e-6_8
Definition at line 47 of file global.f90.
Referenced by physics::elastic_scattering().
type(material_type),dimension(:),allocatable global::mat
Definition at line 26 of file global.f90.
Referenced by add_to_tallies(), allocate_problem(), compute_macro_cross_sections(), deallocate_problem(), physics::elastic_scattering(), finalize_tallies(), physics::get_eidx(), input::read_input(), physics::sample_isotope(), physics::sample_reaction(), physics::sample_region(), and physics::sample_source().
integer global::n_abs = 0.0_8
Definition at line 57 of file global.f90.
Referenced by physics::perform_physics().
integer global::n_fiss = 0.0_8
Definition at line 58 of file global.f90.
Referenced by finalize_tallies(), and physics::perform_physics().
integer global::n_materials
Definition at line 37 of file global.f90.
Referenced by allocate_problem(), compute_macro_cross_sections(), deallocate_problem(), finalize_tallies(), and physics::sample_region().
integer global::n_tallies
Definition at line 36 of file global.f90.
Referenced by add_to_tallies(), allocate_problem(), bank_tallies(), deallocate_problem(), finalize_tallies(), and output::write_output().
type(particle_type) global::neut
Definition at line 25 of file global.f90.
Referenced by add_to_tallies(), physics::elastic_scattering(), physics::perform_physics(), run_problem(), physics::sample_region(), and physics::sample_source().
integer global::nhistories
Definition at line 30 of file global.f90.
Referenced by finalize_tallies(), input::read_input(), and run_problem().
real(8) global::nubar = 2.455_8
Definition at line 50 of file global.f90.
Referenced by add_to_tallies(), and finalize_tallies().
real(8) global::radius
Definition at line 40 of file global.f90.
Referenced by physics::sample_region().
integer global::res_iso
Definition at line 38 of file global.f90.
integer global::seed
Definition at line 31 of file global.f90.
Referenced by initialize(), and input::read_input().
integer global::source_type
Definition at line 32 of file global.f90.
Referenced by input::read_input().
type(tally_type),dimension(:),allocatable global::tal
Definition at line 27 of file global.f90.
Referenced by add_to_tallies(), allocate_problem(), bank_tallies(), deallocate_problem(), finalize_tallies(), and output::write_output().
type(Timer) global::time_init
Definition at line 53 of file global.f90.
Referenced by initialize(), and output::write_output().
type(Timer) global::time_run
Definition at line 54 of file global.f90.
Referenced by run_problem(), and output::write_output().
integer global::VERSION_MAJOR = 0
Definition at line 20 of file global.f90.
Referenced by output::print_heading().
integer global::VERSION_MINOR = 1
Definition at line 21 of file global.f90.
Referenced by output::print_heading().
integer global::VERSION_RELEASE = 1
Definition at line 22 of file global.f90.
Referenced by output::print_heading().