SlowMC: tally Module Reference
tally Module Reference
Contains information about tallying quantities.
Data Types
type tally_type
Functions/Subroutines
subroutine, public set_user_tally (this, Ebins, n, react_type, isotope, region, n_materials, dv)
routine to intialize user-defined tallies
subroutine, public set_spectrum_tally (this, emax, emin, n_materials)
routine to initialize all tallies
subroutine, public set_kinf_tally (this, emax, emin, n_materials)
routine to initiaize kinf nu-fission tally
subroutine, public add_to_tally (this, fact, totxs, E, region)
routine to add quantities during transport of a particle
subroutine, public bank_tally (this)
routine to bank a histories tallies
subroutine, public calculate_statistics (this, n)
routine to compute mean and standard deviation of tallies
subroutine, public deallocate_tally (this)
routine to deallocate tally types
Detailed Description
Contains information about tallying quantities.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine,public tally::add_to_tally (type(tally_type) this, real(8) fact, real(8) totxs, real(8) E, integer region)
routine to add quantities during transport of a particle
Definition at line 170 of file tally.f90.
Referenced by global::add_to_tallies().
subroutine,public tally::bank_tally (type(tally_type) this)
routine to bank a histories tallies
Definition at line 217 of file tally.f90.
Referenced by global::bank_tallies().
subroutine,public tally::calculate_statistics (type(tally_type) this, integer n)
routine to compute mean and standard deviation of tallies
Definition at line 236 of file tally.f90.
Referenced by global::finalize_tallies().
subroutine,public tally::deallocate_tally (type(tally_type) this)
routine to deallocate tally types
Definition at line 255 of file tally.f90.
Referenced by global::deallocate_problem().
subroutine,public tally::set_kinf_tally (type(tally_type) this, real(8) emax, real(8) emin, integer n_materials)
routine to initiaize kinf nu-fission tally
Definition at line 131 of file tally.f90.
subroutine,public tally::set_spectrum_tally (type(tally_type) this, real(8) emax, real(8) emin, integer n_materials)
routine to initialize all tallies
Definition at line 95 of file tally.f90.
Referenced by input::read_input().
subroutine,public tally::set_user_tally (type(tally_type) this, real(8),dimension(n) Ebins, integer n, integer react_type, integer isotope, integer region, integer n_materials, logical dv)
routine to intialize user-defined tallies
Definition at line 43 of file tally.f90.
Referenced by input::read_input().