SlowMC: /mnt/md0/Documents/Documents/Spring2012/211/SlowMC/src/xml-fortran/xmlreader.f90 File Reference
xmlreader.f90 File Reference
Functions/Subroutines
program xmlreader
subroutine get_global_options (attribs, noattribs, strict, global_type, global_name, root_name, dyn_strings)
subroutine set_options (attribs, noattribs, strict, global_type, global_name, root_name, dyn_strings)
subroutine open_tmp_files (lufirst)
subroutine close_tmp_files
subroutine append_files (lufirst)
subroutine merge_files
subroutine write_prolog
subroutine add_begin_loop (checktag, component)
subroutine add_end_loop
subroutine add_variable (component)
subroutine add_typedef (dyn_strings)
subroutine close_typedef (component)
subroutine add_placeholder (dyn_strings)
subroutine close_placeholder
Function Documentation
subroutine xmlreader::add_begin_loop (logical checktag, logical component)
Definition at line 632 of file xmlreader.f90.
Referenced by add_placeholder(), and xmlreader().
subroutine xmlreader::add_end_loop ()
Definition at line 716 of file xmlreader.f90.
Referenced by add_placeholder(), add_typedef(), and write_prolog().
subroutine xmlreader::add_placeholder (logical,intent(in) dyn_strings)
Definition at line 1131 of file xmlreader.f90.
References add_begin_loop(), add_end_loop(), open_tmp_files(), and xmlparse::xml_find_attrib().
Referenced by xmlreader().
subroutine xmlreader::add_typedef (logical,intent(in) dyn_strings)
Definition at line 945 of file xmlreader.f90.
References add_end_loop(), open_tmp_files(), and xmlparse::xml_find_attrib().
Referenced by xmlreader().
subroutine xmlreader::add_variable (logical component)
Definition at line 744 of file xmlreader.f90.
References xmlparse::xml_find_attrib().
Referenced by xmlreader().
subroutine xmlreader::append_files (integer,intent(in) lufirst)
Definition at line 467 of file xmlreader.f90.
Referenced by close_placeholder(), close_typedef(), and xmlreader().
subroutine xmlreader::close_placeholder ()
Definition at line 1223 of file xmlreader.f90.
References append_files(), and close_tmp_files().
Referenced by xmlreader().
subroutine xmlreader::close_tmp_files ()
Definition at line 444 of file xmlreader.f90.
Referenced by close_placeholder(), and close_typedef().
subroutine xmlreader::close_typedef (logical,intent(out) component)
Definition at line 1105 of file xmlreader.f90.
References append_files(), and close_tmp_files().
Referenced by xmlreader().
subroutine xmlreader::get_global_options (character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, logical,intent(inout) strict, logical,intent(inout) global_type, character(len=*),intent(inout) global_name, character(len=*),intent(inout) root_name, logical,intent(inout) dyn_strings)
Definition at line 328 of file xmlreader.f90.
References set_options(), xmlparse::xml_close(), xmlparse::xml_get(), xmlparse::xml_ok(), and xmlparse::xml_open().
Referenced by xmlreader().
subroutine xmlreader::merge_files ()
Definition at line 506 of file xmlreader.f90.
Referenced by xmlreader().
subroutine xmlreader::open_tmp_files (integer,intent(in) lufirst)
Definition at line 420 of file xmlreader.f90.
Referenced by add_placeholder(), add_typedef(), and xmlreader().
subroutine xmlreader::set_options (character(len=*),dimension(:,:),intent(in) attribs, integer,intent(in) noattribs, logical,intent(inout) strict, logical,intent(inout) global_type, character(len=*),intent(inout) global_name, character(len=*),intent(inout) root_name, logical,intent(inout) dyn_strings)
Definition at line 372 of file xmlreader.f90.
Referenced by get_global_options(), and xmlreader().
subroutine xmlreader::write_prolog ()
Definition at line 549 of file xmlreader.f90.
References add_end_loop().
Referenced by xmlreader().
program xmlreader ()
Definition at line 12 of file xmlreader.f90.
References add_begin_loop(), add_placeholder(), add_typedef(), add_variable(), append_files(), close_placeholder(), close_typedef(), get_global_options(), merge_files(), open_tmp_files(), set_options(), write_prolog(), xmlparse::xml_error(), xmlparse::xml_get(), xmlparse::xml_ok(), xmlparse::xml_open(), and xmlparse::xml_options().